disable pipefail

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -94,7 +94,9 @@ jobs:
             echo "nix is not installed"
           fi
       - name: Run om static binary
+        # We need to disable pipefail because the om binary will return a non-zero
         run: |
+            set +o pipefail
             chmod +x ./om
             ./om health | grep "Nix is not installed. Please install Nix: https://nixos.asia/en/install"
 
